[package]
name = "mining"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mining-cuda-sys = { path = "../mining-cuda-sys" }
mining-metal-sys = { path = "../mining-metal-sys" }
mining-opencl-sys = { path = "../mining-opencl-sys" }
argon2.workspace = true
bip39.workspace = true
bs58.workspace = true
ed25519-dalek.workspace = true
ethers-core.workspace = true
ethers-middleware.workspace = true
ethers-providers.workspace = true
ethers-signers.workspace = true
hmac.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true

[lints]
workspace = true
